//%attributes = {}
  //ACTpgs_OnLoad

ARRAY DATE:C224(aACT_ApdosDPFecha;0)
ARRAY TEXT:C222(aACT_ApdosDPPeriodo;0)
ARRAY TEXT:C222(aACT_ApdosDPAlumno;0)
ARRAY REAL:C219(aACT_ApdosDPMonto;0)
ARRAY REAL:C219(aACT_ApdosDPSaldoCargo;0)
ARRAY REAL:C219(aACT_ApdosDPPagadoCargo;0)
ARRAY LONGINT:C221(aACT_ApdosDPIDItem;0)
ARRAY TEXT:C222(aACT_ApdosDPGlosaCargo;0)
ARRAY LONGINT:C221(aIDCta;0)
ARRAY PICTURE:C279(aACT_ApdosDPAfectoPict;0)
C_TEXT:C284(vt_noTarjetaC)
xALSet_Pgs_Desglose 