//%attributes = {}
C_POINTER:C301($1)

READ ONLY:C145([Asignaturas:18])
READ ONLY:C145([Asignaturas_Historico:84])
READ ONLY:C145([Alumnos:2])
READ ONLY:C145([Alumnos_Calificaciones:208])
READ ONLY:C145([Asignaturas_Consolidantes:231])
If (Count parameters:C259=1)
	CREATE SELECTION FROM ARRAY:C640([Asignaturas:18];$1->)
Else 
	ALL RECORDS:C47([Asignaturas:18])
End if 

If (Records in selection:C76([Asignaturas:18])>0)
	$refXMLDoc:=CONDOR_ExportDataGenArchivo ("asignaturas";->$vt_FileName)
	
	ARRAY LONGINT:C221($recNums;0)
	LONGINT ARRAY FROM SELECTION:C647([Asignaturas:18];$recNums)
	$size:=Size of array:C274($recNums)
	
	$l_ProgressProcID:=IT_Progress (1;0;$l_ProgressProcID;__ ("Generando documento con ")+String:C10($size)+__ (" registros de asignaturas..."))
	For ($indice;1;$size)
		KRL_GotoRecord (->[Asignaturas:18];$recNums{$indice};False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"asignatura")
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]auto_uuid:12);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"nombre";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Asignatura:3);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid_profesor";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]profesor_numero:4);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"nivel";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_del_Nivel:6);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"sector";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Sector:9);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"denominacion_interna";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]denominacion_interna:16);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"seleccion_por_sexo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Seleccion_por_sexo:24);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid_curso";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_del_Curso:25);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"abreviatura";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Abreviación:26);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid_firmante";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]profesor_firmante_numero:33);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"cl_codigo_mineduc";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]CHILE_CodigoMineduc:41);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"codigo_interno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Codigo_interno:48);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_semanales";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Horas_Semanales:51);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_anuales";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Horas_Anuales:68);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_efectivas";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Horas_de_clases_efectivas:52);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"orden_general";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]ordenGeneral:105);True:C214;False:C215)
		
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"materia_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Materia_UUID:46);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"plan_especial";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Plan_especial:10);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"electiva";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Electiva:11);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"eninformesinternos";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]En_InformesInternos:14);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"seleccion";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Seleccion:17);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_promedio";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Incide_en_promedio:27);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_promedio_interno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]IncideEnPromedioInterno:64);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"eximible";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Eximible:28);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"numero_grupo_electivo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_del_grupo_electivo:29);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidacion_consubasignaturas";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Consolidacion_ConSubasignaturas:31);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidacion_esconsolidante";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Consolidacion_EsConsolidante:35);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"posicion_en_informes";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]posicion_en_informes_de_notas:36);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"numeroevaluaciones";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_de_evaluaciones:38);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"posicion_en_informes";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]posicion_en_informes_de_notas:36);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"evstyle_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_de_EstiloEvaluacion:39);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"ingresa_esfuerzo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Ingresa_Esfuerzo:40);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"pondera_esfuerzo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Pondera_Esfuerzo:61);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"objetivos_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]ID_Objetivos:43);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"incluida_en_actas";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Incluida_en_Actas:44);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_asistencia";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Incide_en_Asistencia:45);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"resultado_no_calculado";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Resultado_no_calculado:47);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"numero_de_alumnos";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Numero_de_alumnos:49);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidacion_tipoponderacion";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Consolidacion_TipoPonderacion:50);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"promediofinal_texto";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]PromedioFinal_texto:53);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"promediofinaloficial_texto";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]PromedioFinalOficial_texto:67);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"last_number";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]LastNumber:54);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidacion_metodo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Consolidacion_Metodo:55);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"fecha_creacion";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Fecha_de_Creacion:56);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"fecha_modificacion";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Fecha_de_modificacion:15);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidacion_porperiodo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Consolidacion_PorPeriodo:58);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"publicar_enschoolnet";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Publicar_en_SchoolNet:60);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"conobjetivosespecificos";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]ConObjetivosEspecificos:62);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"optativa";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Es_Optativa:70);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"no_oficial";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Asignatura_No_Oficial:71);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"ultimo_archivo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Ultimo_archivo:72);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"grupo_estadistico";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]GrupoEstadistico:89);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"EVAPR_matriz_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]EVAPR_IdMatriz:91);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"EVAPR_esarea";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]EVAPR_EsArea:93);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"notaoficial_conestiloasignatura";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]NotaOficial_conEstiloAsignatura:95);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"porcentaje_aprobados";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]PorcentajeAprobados:103);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"nivel_jerarquico";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]nivel_jerarquico:107);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"ponderacionenpromediooficial";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]PonderacionEnPromedioOF:109);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"ponderacionenpromediointerno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]PonderacionEnPromedioINT:110);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"creditos";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Creditos:111);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"objetivosxalumno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]ObjetivosxAlumno:112);False:C215;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"opciones";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Opciones:57);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"configuracion";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]Configuracion:63);True:C214;False:C215)
		CONDOR_ExportSAXCreateNode ($refXMLDoc;"opcionescontroles_examenes";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas:18]OpcionesControles_y_Examenes:106);True:C214;False:C215)
		QUERY:C277([Asignaturas_Consolidantes:231];[Asignaturas_Consolidantes:231]ID_AsignaturaMadre:1=[Asignaturas:18]Numero:1)  //consolidantes (es madre de)
		CREATE SET:C116([Asignaturas_Consolidantes:231];"$consolidantes")
		QUERY:C277([Asignaturas_Consolidantes:231];[Asignaturas_Consolidantes:231]ID_ParentRecord:5=[Asignaturas:18]Numero:1)  //consolida en(es hija de)
		CREATE SET:C116([Asignaturas_Consolidantes:231];"$consolidaen")
		If ((Records in set:C195("$consolidantes")>0) | (Records in set:C195("$consolidaen")>0))
			CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidaciones")
			If (Records in set:C195("$consolidantes")>0)
				USE SET:C118("$consolidantes")
				ARRAY LONGINT:C221($al_consolidantes;0)
				LONGINT ARRAY FROM SELECTION:C647([Asignaturas_Consolidantes:231];$al_consolidantes)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidantes")
				For ($x;1;Size of array:C274($al_consolidantes))
					KRL_GotoRecord (->[Asignaturas_Consolidantes:231];$al_consolidantes{$x})
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidante")
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"asignatura";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Consolidantes:231]ID_ParentRecord:5);False:C215;False:C215)
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"periodo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Consolidantes:231]Periodo:3);False:C215;False:C215)
					SAX CLOSE XML ELEMENT:C854($refXMLDoc)
				End for 
				SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre cosolidantes
			End if 
			If (Records in set:C195("$consolidaen")>0)
				USE SET:C118("$consolidaen")
				ARRAY LONGINT:C221($al_consolidaen;0)
				LONGINT ARRAY FROM SELECTION:C647([Asignaturas_Consolidantes:231];$al_consolidaen)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidaen")
				For ($x;1;Size of array:C274($al_consolidaen))
					KRL_GotoRecord (->[Asignaturas_Consolidantes:231];$al_consolidaen{$x})
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"consolidante")
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"asignatura";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Consolidantes:231]ID_AsignaturaMadre:1);False:C215;False:C215)
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"periodo";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Consolidantes:231]Periodo:3);False:C215;False:C215)
					SAX CLOSE XML ELEMENT:C854($refXMLDoc)
				End for 
				SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre consolida en
			End if 
			SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre consolidaciones
		End if 
		SET_ClearSets ("$consolidantes";"$consolidaen")
		EV2_RegistrosDeLaAsignatura ([Asignaturas:18]Numero:1)
		If (Records in selection:C76([Alumnos_Calificaciones:208])>0)
			ARRAY LONGINT:C221($al_alumnosCalificaciones;0)
			LONGINT ARRAY FROM SELECTION:C647([Alumnos_Calificaciones:208];$al_alumnosCalificaciones)
			CONDOR_ExportSAXCreateNode ($refXMLDoc;"alumnos")
			For ($x;1;Size of array:C274($al_alumnosCalificaciones))
				KRL_GotoRecord (->[Alumnos_Calificaciones:208];$al_alumnosCalificaciones{$x})
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"alumno";True:C214;CONDOR_ExportDataTransformer (->[Alumnos_Calificaciones:208]ID_Alumno:6);False:C215;False:C215)
			End for 
			SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre alumnos
		End if 
		
		READ ONLY:C145([Asignaturas_Historico:84])
		QUERY:C277([Asignaturas_Historico:84];[Asignaturas_Historico:84]ID_AsignaturaOriginal:30=[Asignaturas:18]Numero:1)
		If (Records in selection:C76([Asignaturas_Historico:84])>0)
			CONDOR_ExportSAXCreateNode ($refXMLDoc;"historicos")
			ORDER BY:C49([Asignaturas_Historico:84];[Asignaturas_Historico:84]Año:5;>)
			ARRAY LONGINT:C221($al_asigshistoricos;0)
			LONGINT ARRAY FROM SELECTION:C647([Asignaturas_Historico:84];$al_asigshistoricos)
			For ($x;1;Size of array:C274($al_asigshistoricos))
				KRL_GotoRecord (->[Asignaturas_Historico:84];$al_asigshistoricos{$x})
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"historico")
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"materia_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Materia_UUID:45);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"nivel";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Nivel:4);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"year";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Año:5);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_promedio";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Promediable:6);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_promedio_interno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]IncideEnPromedioInterno:27);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"incluida_en_actas";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Incluida_En_Actas:7);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"electiva";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Electiva:10);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"posicion_en_informes";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Order:11);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid_profesor";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Profesor_Numero:12);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"uuid_curso";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Curso:14);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_semanales";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Horas_Semanales:35);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_anuales";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]HorasAnuales:29);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"horas_efectivas";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Horas_Efectivas:36);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"grupo_estadistico";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Grupo_Estadistico:37);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"optativa";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Optativa:24);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"sector";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Sector:38);True:C214;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"orden_general";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]OrdenGeneral:42);True:C214;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"eninformesinternos";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]EnInformesInternos:43);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"ponderacionenpromediooficial";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]PonderacionEnPromedioOF:26);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"ponderacionenpromediointerno";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]PonderacionPromedioINT:23);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"incide_en_asistencia";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]Incide_en_Asistencia:28);False:C215;False:C215)
				CONDOR_ExportSAXCreateNode ($refXMLDoc;"evstyle_uuid";True:C214;CONDOR_ExportDataTransformer (->[Asignaturas_Historico:84]ID_EstiloEvalAsignatura:25);False:C215;False:C215)
				QUERY:C277([Alumnos_Calificaciones:208];[Alumnos_Calificaciones:208]ID_HistoricoAsignatura:493=[Asignaturas_Historico:84]ID_RegistroHistorico:1)
				If (Records in selection:C76([Alumnos_Calificaciones:208])>0)
					ARRAY LONGINT:C221($al_alumnosCalificaciones;0)
					LONGINT ARRAY FROM SELECTION:C647([Alumnos_Calificaciones:208];$al_alumnosCalificaciones)
					CONDOR_ExportSAXCreateNode ($refXMLDoc;"alumnos")
					For ($y;1;Size of array:C274($al_alumnosCalificaciones))
						KRL_GotoRecord (->[Alumnos_Calificaciones:208];$al_alumnosCalificaciones{$y})
						CONDOR_ExportSAXCreateNode ($refXMLDoc;"alumno";True:C214;CONDOR_ExportDataTransformer (->[Alumnos_Calificaciones:208]ID_Alumno:6);False:C215;False:C215)
					End for 
					SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre alumnos
				End if 
				SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre historico
			End for 
			SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre historicos
		End if 
		
		SAX CLOSE XML ELEMENT:C854($refXMLDoc)  //cierre asignatura
		$l_ProgressProcID:=IT_Progress (0;$l_ProgressProcID;$indice/$size;__ ("Exportando asignatura ")+[Asignaturas:18]denominacion_interna:16+" - "+[Asignaturas:18]Curso:5+", "+String:C10($indice)+__ (" de ")+String:C10($size)+"...")
	End for 
	$l_ProgressProcID:=IT_Progress (-1;$l_ProgressProcID)
	
	SN3_CloseXMLCompress ("";$vt_FileName;"sax";$refXMLDoc)
End if 

