//%attributes = {}
C_LONGINT:C283($i;$j;$p)
C_DATE:C307($date)
If (USR_GetUserID <0)
	
	$ok:=CD_Dlog (0;"Se dispone a incrementar el año de esta base de datos, ¿Está seguro?";"";"Si";"No")
	If ($ok=1)
		$t:=IT_StartTimer 
		$oldYear:=<>gYear
		DBU_EstableceAñoEscolarActual (<>gYear+1)
		
		$p:=IT_UThermometer (1;0;"Incrementando campos tipo fecha...")
		For ($i;1;Get last table number:C254)
			If (Is table number valid:C999($i))
				IT_UThermometer (0;$p;"Incrementando campos tipo fecha de la tabla "+Table name:C256($i)+"...")
				READ WRITE:C146(Table:C252($i)->)
				ALL RECORDS:C47(Table:C252($i)->)
				While (Not:C34(End selection:C36(Table:C252($i)->)))
					For ($j;1;Get last field number:C255($i))
						If (Is field number valid:C1000($i;$j))
							If (Type:C295(Field:C253($i;$j)->)=Is date:K8:7)
								$date:=Field:C253($i;$j)->
								If ($date#!00-00-00!)
									$date:=Add to date:C393($date;1;0;0)
									Field:C253($i;$j)->:=$date
									SAVE RECORD:C53(Table:C252($i)->)
								End if 
							End if 
						End if 
					End for 
					NEXT RECORD:C51(Table:C252($i)->)
				End while 
				KRL_UnloadReadOnly (Table:C252($i))
			End if 
		End for 
		IT_UThermometer (-2;$p)
		
		dbu_ReparaConducta 
		
		READ WRITE:C146(*)
		$p:=IT_UThermometer (1;0;"Incrementando año en históricos Alumnos_Actividades...")
		QUERY:C277([Alumnos_Actividades:28];[Alumnos_Actividades:28]Año:3<$oldYear)
		ORDER BY:C49([Alumnos_Actividades:28];[Alumnos_Actividades:28]Año:3;<)
		APPLY TO SELECTION:C70([Alumnos_Actividades:28];[Alumnos_Actividades:28]Año:3:=[Alumnos_Actividades:28]Año:3+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Anotaciones...")
		QUERY:C277([Alumnos_Anotaciones:11];[Alumnos_Anotaciones:11]Año:11<$oldYear)
		ORDER BY:C49([Alumnos_Anotaciones:11];[Alumnos_Anotaciones:11]Año:11;<)
		APPLY TO SELECTION:C70([Alumnos_Anotaciones:11];[Alumnos_Anotaciones:11]Año:11:=[Alumnos_Anotaciones:11]Año:11+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Atrasos...")
		QUERY:C277([Alumnos_Atrasos:55];[Alumnos_Atrasos:55]Año:6<$oldYear)
		ORDER BY:C49([Alumnos_Atrasos:55];[Alumnos_Atrasos:55]Año:6;<)
		APPLY TO SELECTION:C70([Alumnos_Atrasos:55];[Alumnos_Atrasos:55]Año:6:=[Alumnos_Atrasos:55]Año:6+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Castigos...")
		QUERY:C277([Alumnos_Castigos:9];[Alumnos_Castigos:9]Año:5<$oldYear)
		ORDER BY:C49([Alumnos_Castigos:9];[Alumnos_Castigos:9]Año:5;<)
		APPLY TO SELECTION:C70([Alumnos_Castigos:9];[Alumnos_Castigos:9]Año:5:=[Alumnos_Castigos:9]Año:5+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Inasistencias...")
		QUERY:C277([Alumnos_Inasistencias:10];[Alumnos_Inasistencias:10]Año:8<$oldYear)
		ORDER BY:C49([Alumnos_Inasistencias:10];[Alumnos_Inasistencias:10]Año:8;<)
		APPLY TO SELECTION:C70([Alumnos_Inasistencias:10];[Alumnos_Inasistencias:10]Año:8:=[Alumnos_Inasistencias:10]Año:8+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Licencias...")
		QUERY:C277([Alumnos_Licencias:73];[Alumnos_Licencias:73]Año:9<$oldYear)
		ORDER BY:C49([Alumnos_Licencias:73];[Alumnos_Licencias:73]Año:9;<)
		APPLY TO SELECTION:C70([Alumnos_Licencias:73];[Alumnos_Licencias:73]Año:9:=[Alumnos_Licencias:73]Año:9+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Suspensiones...")
		QUERY:C277([Alumnos_Suspensiones:12];[Alumnos_Suspensiones:12]Año:1<$oldYear)
		ORDER BY:C49([Alumnos_Suspensiones:12];[Alumnos_Suspensiones:12]Año:1;<)
		APPLY TO SELECTION:C70([Alumnos_Suspensiones:12];[Alumnos_Suspensiones:12]Año:1:=[Alumnos_Suspensiones:12]Año:1+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_ComplementosEvaluacion...")
		QUERY:C277([Alumnos_ComplementoEvaluacion:209];[Alumnos_ComplementoEvaluacion:209]Año:3<$oldYear)
		ORDER BY:C49([Alumnos_ComplementoEvaluacion:209];[Alumnos_ComplementoEvaluacion:209]Año:3;<)
		APPLY TO SELECTION:C70([Alumnos_ComplementoEvaluacion:209];[Alumnos_ComplementoEvaluacion:209]Año:3:=[Alumnos_ComplementoEvaluacion:209]Año:3+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Calificaciones...")
		QUERY:C277([Alumnos_Calificaciones:208];[Alumnos_Calificaciones:208]Año:3<$oldYear)
		ORDER BY:C49([Alumnos_Calificaciones:208];[Alumnos_Calificaciones:208]Año:3;<)
		APPLY TO SELECTION:C70([Alumnos_Calificaciones:208];[Alumnos_Calificaciones:208]Año:3:=[Alumnos_Calificaciones:208]Año:3+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_EvaluacionAprendizajes...")
		QUERY:C277([Alumnos_EvaluacionAprendizajes:203];[Alumnos_EvaluacionAprendizajes:203]Año:77<$oldYear)
		ORDER BY:C49([Alumnos_EvaluacionAprendizajes:203];[Alumnos_EvaluacionAprendizajes:203]Año:77;<)
		APPLY TO SELECTION:C70([Alumnos_EvaluacionAprendizajes:203];[Alumnos_EvaluacionAprendizajes:203]Año:77:=[Alumnos_EvaluacionAprendizajes:203]Año:77+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_SintesisAnual...")
		QUERY:C277([Alumnos_SintesisAnual:210];[Alumnos_SintesisAnual:210]Año:2<$oldYear)
		ORDER BY:C49([Alumnos_SintesisAnual:210];[Alumnos_SintesisAnual:210]Año:2;<)
		APPLY TO SELECTION:C70([Alumnos_SintesisAnual:210];[Alumnos_SintesisAnual:210]Año:2:=[Alumnos_SintesisAnual:210]Año:2+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Asignaturas_SintesisAnual...")
		QUERY:C277([Asignaturas_SintesisAnual:202];[Asignaturas_SintesisAnual:202]Año:3<$oldYear)
		ORDER BY:C49([Asignaturas_SintesisAnual:202];[Asignaturas_SintesisAnual:202]Año:3;<)
		APPLY TO SELECTION:C70([Asignaturas_SintesisAnual:202];[Asignaturas_SintesisAnual:202]Año:3:=[Asignaturas_SintesisAnual:202]Año:3+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Cursos_SintesisAnual...")
		QUERY:C277([Cursos_SintesisAnual:63];[Cursos_SintesisAnual:63]Año:2<$oldYear)
		ORDER BY:C49([Cursos_SintesisAnual:63];[Cursos_SintesisAnual:63]Año:2;<)
		APPLY TO SELECTION:C70([Cursos_SintesisAnual:63];[Cursos_SintesisAnual:63]Año:2:=[Cursos_SintesisAnual:63]Año:2+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos BU_Rutas...")
		QUERY:C277([BU_Rutas:26];[BU_Rutas:26]Año:2<$oldYear)
		ORDER BY:C49([BU_Rutas:26];[BU_Rutas:26]Año:2;<)
		APPLY TO SELECTION:C70([BU_Rutas:26];[BU_Rutas:26]Año:2:=[BU_Rutas:26]Año:2+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Alumnos_Historico...")
		QUERY:C277([Alumnos_Historico:25];[Alumnos_Historico:25]Año:2<$oldYear)
		ORDER BY:C49([Alumnos_Historico:25];[Alumnos_Historico:25]Año:2;<)
		APPLY TO SELECTION:C70([Alumnos_Historico:25];[Alumnos_Historico:25]Año:2:=[Alumnos_Historico:25]Año:2+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos Asignaturas_Historico...")
		QUERY:C277([Asignaturas_Historico:84];[Asignaturas_Historico:84]Año:5<$oldYear)
		ORDER BY:C49([Asignaturas_Historico:84];[Asignaturas_Historico:84]Año:5;<)
		APPLY TO SELECTION:C70([Asignaturas_Historico:84];[Asignaturas_Historico:84]Año:5:=[Asignaturas_Historico:84]Año:5+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos xxSTR_DatosDeCierre...")
		QUERY:C277([xxSTR_DatosDeCierre:24];[xxSTR_DatosDeCierre:24]Year:1<$oldYear)
		ORDER BY:C49([xxSTR_DatosDeCierre:24];[xxSTR_DatosDeCierre:24]Year:1;<)
		APPLY TO SELECTION:C70([xxSTR_DatosDeCierre:24];[xxSTR_DatosDeCierre:24]Year:1:=[xxSTR_DatosDeCierre:24]Year:1+1)
		APPLY TO SELECTION:C70([xxSTR_DatosDeCierre:24];[xxSTR_DatosDeCierre:24]NombreAgnoEscolar:5:=String:C10([xxSTR_DatosDeCierre:24]Year:1))
		IT_UThermometer (0;$p;"Incrementando año en históricos xxSTR_HistoricoEstilosEval...")
		QUERY:C277([xxSTR_HistoricoEstilosEval:88];[xxSTR_HistoricoEstilosEval:88]Año:2<$oldYear)
		ORDER BY:C49([xxSTR_HistoricoEstilosEval:88];[xxSTR_HistoricoEstilosEval:88]Año:2;<)
		APPLY TO SELECTION:C70([xxSTR_HistoricoEstilosEval:88];[xxSTR_HistoricoEstilosEval:88]Año:2:=[xxSTR_HistoricoEstilosEval:88]Año:2+1)
		IT_UThermometer (0;$p;"Incrementando año en históricos xxSTR_HistoricoNiveles...")
		QUERY:C277([xxSTR_HistoricoNiveles:191];[xxSTR_HistoricoNiveles:191]Año:2<$oldYear)
		ORDER BY:C49([xxSTR_HistoricoNiveles:191];[xxSTR_HistoricoNiveles:191]Año:2;<)
		APPLY TO SELECTION:C70([xxSTR_HistoricoNiveles:191];[xxSTR_HistoricoNiveles:191]Año:2:=[xxSTR_HistoricoNiveles:191]Año:2+1)
		IT_UThermometer (-2;$p)
		
		ALL RECORDS:C47([xxSTR_Constants:1])
		[xxSTR_Constants:1]NombreEjercicio:29:=String:C10(<>gYear)
		SAVE RECORD:C53([xxSTR_Constants:1])
		KRL_UnloadReadOnly (->[xxSTR_Constants:1])
		
		C_LONGINT:C283($r)
		C_TEXT:C284($result)
		WEB SERVICE SET PARAMETER:C777("codpais";<>vtXS_CountryCode)
		WEB SERVICE SET PARAMETER:C777("rolbd";<>gRolBD)
		$p:=IT_UThermometer (1;0;"Eliminando datos en SchoolNet...")
		$err:=SN3_CallWebService ("sn3ws_eliminaciondatos_proceso.eliminaTodo")
		IT_UThermometer (-2;$p)
		
		SN3_SendData2SchoolNet (True:C214;True:C214)
		
		IT_StopTimer ($t)
		ALERT:C41("A continuación SchoolTrack se cerrará. Por favor ejecute SchoolTrack nuevamente para disfrutar de su base año "+String:C10(<>gYear)+".")
		QUIT 4D:C291
	End if 
End if 