AL_ExitCell (xALP_EstadosFDP)
_O_DISABLE BUTTON:C193(bDelEFP)
AL_UpdateArrays (xALP_EstadosFDP;0)
ACTcfg_OpcionesEstadosPagos ("InsertaNuevoEstado";->vlACT_idFormaDePago)
AL_UpdateArrays (xALP_EstadosFDP;-2)
ACTcfg_OpcionesEstadosPagos ("ColorFormasDePagoXDefecto")
ACTcfg_OpcionesEstadosPagos ("EstadoXDefecto")
GOTO OBJECT:C206(xALP_EstadosFDP)
AL_GotoCell (xALP_EstadosFDP;1;Size of array:C274(alACT_estadosID))