AL_UpdateArrays (xALP_Tables;0)
vs_Text1:="Valores en tabla "+ST_Uppercase (pLists{plists})
FORM SET OUTPUT:C54([xShell_List:39];"Print")
PRINT SELECTION:C60([xShell_List:39])
AL_UpdateArrays (xALP_Tables;-2)