
If (Form event:C388=On Clicked:K2:4)
	GET LIST ITEM:C378(Self:C308->;Selected list items:C379(Self:C308->);$itemRef;$itemText)
	If (Contextual click:C713)
		$popText:="Establecer lengüeta como por defecto..."
		$choice:=Pop up menu:C542($popText)
		If ($choice=1)
			PREF_Set (USR_GetUserID ;"lenguetaSalud";String:C10($itemRef))
		End if 
		OBJECT SET VISIBLE:C603(*;"Observaciones_Salud@";False:C215)
		OBJECT SET VISIBLE:C603(*;"camposMedicos@";False:C215)
		OBJECT SET VISIBLE:C603(*;"tratamientos";False:C215)
		OBJECT SET VISIBLE:C603(*;"buttonsTratamiento@";False:C215)
		Case of 
			: ($itemRef=-1)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;True:C214)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";False:C215)
				_O_DISABLE BUTTON:C193(bDelSalud_Aparato)
				IT_SetButtonState (USR_checkRights ("M";->[Alumnos_FichaMedica:13]);->bAddSalud_Aparato)
				AL_UpdateArrays (xALP_Aparatos;-2)
				AL_SetLine (xALP_Aparatos;0)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";True:C214)
				OBJECT SET VISIBLE:C603(*;"buttonsMedicos@";False:C215)
			: ($itemRef=-2)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;False:C215)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";True:C214)
				_O_DISABLE BUTTON:C193(bDelMedico)
				IT_SetButtonState ((USR_checkRights ("M";->[Alumnos_FichaMedica:13]));->bAddMedico)
				  //AL_UpdateArrays (xALP_Medicos;-2)
				  //AL_SetLine (xALP_Medicos;0)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsMedicos@";True:C214)
				OBJECT SET VISIBLE:C603(*;"camposMedicos@";True:C214)
				GOTO OBJECT:C206(vtNombreMedico)
			Else 
				AL_SetScroll (xALP_Aparatos;0;0)
				  //AL_SetScroll (xALP_Medicos;0;0)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;False:C215)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";False:C215)
				OBJECT SET VISIBLE:C603(*;"Observaciones_Salud@";False:C215)
				OBJECT SET VISIBLE:C603(Field:C253(13;$itemRef)->;True:C214)
				OBJECT SET VISIBLE:C603(bDelSalud_Aparato;False:C215)
				OBJECT SET VISIBLE:C603(bAddSalud_Aparato;False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsMedicos@";False:C215)
				OBJECT SET VISIBLE:C603(*;"tratamientos";False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsTratamiento@";False:C215)
				GOTO OBJECT:C206(Field:C253(13;$itemRef)->)
		End case 
		vl_LastHealthItemSelected:=$itemRef
		REDRAW WINDOW:C456
	Else 
		OBJECT SET VISIBLE:C603(*;"Observaciones_Salud@";False:C215)
		OBJECT SET VISIBLE:C603(*;"camposMedicos@";False:C215)
		OBJECT SET VISIBLE:C603(*;"tratamientos";False:C215)
		OBJECT SET VISIBLE:C603(*;"buttonsTratamiento@";False:C215)
		Case of 
			: ($itemRef=-1)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;True:C214)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";False:C215)
				_O_DISABLE BUTTON:C193(bDelSalud_Aparato)
				IT_SetButtonState (USR_checkRights ("M";->[Alumnos_FichaMedica:13]);->bAddSalud_Aparato)
				AL_UpdateArrays (xALP_Aparatos;-2)
				AL_SetLine (xALP_Aparatos;0)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";True:C214)
				  //OBJECT SET VISIBLE(*;"buttonsMedicos@";False)
			: ($itemRef=-2)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;False:C215)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";True:C214)
				  //DISABLE BUTTON(bDelMedico)
				  //IT_SetButtonState ((USR_checkRights ("M";->[Alumnos_FichaMedica]));->bAddMedico)
				  //AL_UpdateArrays (xALP_Medicos;-2)
				  //AL_SetLine (xALP_Medicos;0)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";False:C215)
				  //OBJECT SET VISIBLE(*;"buttonsMedicos@";True)
				  //OBJECT SET VISIBLE(*;"camposMedicos@";True)
				  //GOTO OBJECT(vtNombreMedico)
			: ($itemRef=18)
				OBJECT SET VISIBLE:C603(*;"buttonsTratamiento@";True:C214)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;False:C215)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";False:C215)
				OBJECT SET VISIBLE:C603(*;"tratamientos";True:C214)
			Else 
				AL_SetScroll (xALP_Aparatos;0;0)
				  //AL_SetScroll (xALP_Medicos;0;0)
				OBJECT SET VISIBLE:C603(xALP_Aparatos;False:C215)
				OBJECT SET VISIBLE:C603(*;"listaMedicos";False:C215)
				OBJECT SET VISIBLE:C603(*;"Observaciones_Salud@";False:C215)
				OBJECT SET VISIBLE:C603(Field:C253(13;$itemRef)->;True:C214)
				OBJECT SET VISIBLE:C603(bDelSalud_Aparato;False:C215)
				OBJECT SET VISIBLE:C603(bAddSalud_Aparato;False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsAparatos@";False:C215)
				  //OBJECT SET VISIBLE(*;"buttonsMedicos@";False)
				GOTO OBJECT:C206(Field:C253(13;$itemRef)->)
				OBJECT SET VISIBLE:C603(*;"tratamientos";False:C215)
				OBJECT SET VISIBLE:C603(*;"buttonsTratamiento@";False:C215)
		End case 
		vl_LastHealthItemSelected:=$itemRef
		REDRAW WINDOW:C456
	End if 
End if 