APPEND TO ARRAY:C911(atSTWA2_Usuario;"Seleccione usuario")
APPEND TO ARRAY:C911(adSTWA2_fechadesde;Current date:C33(*))
APPEND TO ARRAY:C911(adSTWA2_fechahasta;Current date:C33(*))
APPEND TO ARRAY:C911(atSTWA2_Asignaturas;"")
APPEND TO ARRAY:C911(atSTWA2_Remplaza;"")
APPEND TO ARRAY:C911(atSTWA2_IDReemplaza;"")
APPEND TO ARRAY:C911(atSTWA2_IDUsuario;"")
APPEND TO ARRAY:C911(atSTWA2_AsignaturasID;"")
